var markerMap=new Map,tailKey=null;
function createMarker(a){try{if(markerMap.containsKey(a.Key))return baiduMapException(2112,null,a.Key),null;var b=new BMap.Point(a.PointX,a.PointY),d=null==a.Title?null:a.Title,e=null==a.Label?null:a.Label,c=null==a.Info?null:a.Info,g=null;null!=a.Icon&&(null!=a.Icon.DefaultIcon?g=getDefaultIcon(a.Icon.DefaultIcon):null!=a.Icon.ImageUrl&&""!=a.Icon.ImageUrl&&(g=createIcon(a.Icon)));var f=new BMap.Marker(b,{title:a.Title,icon:g});null!=e&&f.setLabel(new BMap.Label(e,{offset:new BMap.Size(DEFAULT_LABEL_OFFSETX,
DEFAULT_LABEL_OFFSETY)}));f.addEventListener("click",onMarkerClick);f.addEventListener("dblclick",onMarkerDbClick);f.mtitle=d;f.minfo=c;markerMap.put(a.Key,f);return f}catch(h){return baiduMapException(2211,h,a.Key),null}}function initMarkerAndshown(a){try{objs=eval("("+a+")")}catch(b){b instanceof SyntaxError&&baiduMapException(2111,b,a);return}for(i=0;i<objs.length;i++)obj=objs[i],a=createMarker(obj),null!=a&&map.addOverlay(a)}
function deleteMarker(a){a=eval(a);for(i=0;i<a.length;i++){var b=markerMap.remove(a[i]);map.removeOverlay(b)}}function deleteAllMarker(){for(i=0;i<markerMap.size();i++){var a=markerMap.element(i).value;null!=a.getMap()&&map.removeOverlay(a)}markerMap.clear()}
function updateMarkerWithoutInit(a,b,d,e,c,g){var f=markerMap.get(a);if(null==f)return baiduMapException(2122,null,a),!1;var h=f.getPosition();null==b?null:h.lng=b;null==d?null:h.lat=d;f.setPosition(h);a==tailKey&&pointMarker(a);null!=e&&(f.setTitle(e),f.mtitle=e);null!=c&&(a=f.getLabel(),""==c&&f.setLabel(null),null!=a?a.setContent(c):f.setLabel(new BMap.Label(c,{offset:new BMap.Size(DEFAULT_LABEL_OFFSETX,DEFAULT_LABEL_OFFSETY)})));if(null!=g){f.minfo=g;c=f.minfo;g=f.mtitle;if(null==c||""==c)c=DEFAULT_INFOWINDOW_NULLINFO;
null==g&&(g="");mInfoWindow.marker==f&&(mInfoWindow.setTitle(g),mInfoWindow.setContent(c));mInfoWindow2.marker==f&&(mInfoWindow2.setTitle(g),mInfoWindow2.setContent(c))}return!0}
function updateMarker(a){try{var b=eval("("+a+")")}catch(d){return baiduMapException(2121,d,a),!1}for(i=0;i<b.length;i++){a=b[i];var e=markerMap.get(a.Key);if(null==e)e=createMarker(a),map.addOverlay(e);else{var c=e.getPosition();null==a.PointX?null:c.lng=a.PointX;null==a.PointY?null:c.lat=a.PointY;e.setPosition(c);a.Key==tailKey&&pointMarker(a.Key);null!=a.Title&&(e.setTitle(a.Title),e.mtitle=a.Title);null!=a.Label&&(c=e.getLabel(),""==a.Label&&e.setLabel(null),null!=c?(c.setContent(a.Label),e.setLabel(c)):
e.setLabel(new BMap.Label(a.Label,{offset:new BMap.Size(DEFAULT_LABEL_OFFSETX,DEFAULT_LABEL_OFFSETY)})));if(null!=a.Info&&(e.minfo=a.Info,mInfoWindow.marker==e)){var c=e.minfo,g=e.mtitle;if(null==c||""==c)c=DEFAULT_INFOWINDOW_NULLINFO;null==g&&(g="");mInfoWindow.setTitle(g);mInfoWindow.setContent(c)}c=null;null!=a.Icon&&(null!=a.Icon.DefaultIcon?c=getDefaultIcon(a.Icon.DefaultIcon):null!=a.Icon.ImageUrl&&""!=a.Icon.ImageUrl&&(c=createIcon(a.Icon)));e.setIcon(c)}}}
function getMarkerKeys(){return markerMap.keys().toString()}function isMarkerExist(a){return markerMap.containsKey(a)}function getMarkerKeysOnShown(){var a=[],b=0;for(i=0;i<markerMap.size();i++){var d=markerMap.element(i).value;null!=d.getMap()&&d.isVisible()&&(a[b++]=markerMap.element(i).key)}return a.toString()}
function deleteMarkersNotShown(){for(i=0;i<markerMap.size();i++){var a=markerMap.element(i).value;null==a.getMap()?markerMap.removebyindex(i):a.isVisibel()||(map.removeOverlay(a),markerMap.removebyindex(i))}}function showMarkers(a){a=eval(a);for(i=0;i<a.length;i++){var b=markerMap.get(a[i]);null!=b?(null==b.getMap&&map.addOverlay(b),b.isVisible()||b.show()):baiduMapException(2131,null,a[i])}}
function hiddenMarkers(a){a=eval(a);for(i=0;i<a.length;i++){var b=markerMap.get(a[i]);null!=b?b.hide():baiduMapException(2132,null,a[i])}}function showAllMarkers(){for(i=0;i<markerMap.size();i++){var a=markerMap.element(i).value;null!=a&&(null==a.getMap&&map.addOverlay(a),a.isVisible()||a.show())}}function hiddenAllMarkers(){for(i=0;i<markerMap.size();i++){var a=markerMap.element(i).value;null!=a&&a.hide()}}
function pointMarker(a){var b=markerMap.get(a);if(null==b)return baiduMapException(2133,null,a),!1;if(null==b.getMap()||!b.isVisible())return baiduMapException(2134,null,a),!1;a=b.getPosition();map.panTo(a);return!0}function isMarkerVisible(a){a=markerMap.get(a);return null==a||null==a.getMap()?!1:a.isVisible()?!0:!1}function getMarkerpoint(a){a=markerMap.get(a);if(null==a)return!1;a=a.getPosition();return String(a.lng+","+a.lat)}
function getMarkerTitle(a){a=markerMap.get(a);return null==a?"":null!=a.mtitle?a.mtitle:""}function getMarkerLabel(a){a=markerMap.get(a);return null==a?"":null!=a.getLabel()?a.getLabel().content:""}function getMarkerInfo(a){a=markerMap.get(a);return null==a?"":null!=a.minfo?a.minfo:""}function showMarkerLabel(a){a=eval(a);for(i=0;i<a.length;i++){var b=markerMap.get(a[i]);null!=b&&(b=b.getLabel(),null!=b&&b.show())}}
function hiddenMarkerLabel(a){a=eval(a);for(i=0;i<a.length;i++){var b=markerMap.get(a[i]);null!=b&&b.isVisible()&&(b=b.getLabel(),null!=b&&b.hide())}}function showAllMarkerLabel(){for(i=0;i<markerMap.size();i++){var a=markerMap.element(i).value;null!=a.getMap()&&(a=a.getLabel(),null!=a&&a.show())}}function hiddenAllMarkerLabel(){for(i=0;i<markerMap.size();i++){var a=markerMap.element(i).value;null!=a.getMap()&&a.isVisible()&&(a=a.getLabel(),null!=a&&a.hide())}}
function updateMarkerIcon(a,b){try{var d=eval("("+b+")")}catch(e){return!1}var c=markerMap.get(a);if(null==c)return!1;c.setIcon(createIcon(d.Icon));return!0}function updateMakerWithDefaultIcon(a,b){var d=markerMap.get(a);if(null==d)return!1;d.setIcon(getDefaultIcon(b));return!0}
function openMarkerInfoWindow(a){a=markerMap.get(a);if(null!=a){var b=a.minfo,d=a.mtitle;if(null==b||""==b)b=DEFAULT_INFOWINDOW_NULLINFO;null==d&&(d="");mInfoWindow.setTitle(d);mInfoWindow.setContent(b);a.openInfoWindow(mInfoWindow);mInfoWindow.marker=a}}function closeInfoWindow(){mInfoWindow.hide()}function tailMarker(a){if(null==a||""==a)return tailKey="",!0;if(a==tailKey)return!0;if(!markerMap.containsKey(a))return baiduMapException(2135,null,a),!1;tailKey=a;pointMarker(a);return!0}
function getTailMarker(){return tailKey}function setMarkerMouseOver(a){a=markerMap.get(a);null!=a&&(a.addEventListener("mouseover",onMarkerMouseOver),a.addEventListener("mouseout",onMarkerMouseOut),a.removeEventListener("click",onMarkerClick))}function removeMarkerMouseOver(a){a=markerMap.get(a);null!=a&&(a.removeEventListener("mouseover",onMarkerMouseOver),a.removeEventListener("mouseout",onMarkerMouseOut),a.addEventListener("click",onMarkerClick))}
function onMarkerMouseOver(a){if(mInfoWindow.marker!=a.target){var b=a.target.minfo,d=a.target.mtitle;if(null==b||""==b)b=DEFAULT_INFOWINDOW_NULLINFO;null==d&&(d="");mInfoWindow2.setTitle(d);mInfoWindow2.setContent(b);a.target.openInfoWindow(mInfoWindow2);mInfoWindow2.marker=a.target}}function onMarkerMouseOut(a){mInfoWindow2.hide()}
function onMarkerClick(a){var b=a.target.minfo,d=a.target.mtitle;if(null==b||""==b)b=DEFAULT_INFOWINDOW_NULLINFO;null==d&&(d="");mInfoWindow.setTitle(d);mInfoWindow.setContent(b);a.target.openInfoWindow(mInfoWindow);mInfoWindow.marker=a.target}function onMarkerRightClick(a){}function onMarkerDbClick(a){0!=DEFAULT_MARKER_DBCLICK_ZOOM&&(map.getZoom()<DEFAULT_MARKER_DBCLICK_ZOOM?map.setZoom(DEFAULT_MARKER_DBCLICK_ZOOM):map.setZoom(map.getZoom()+1),map.panTo(a.target.getPosition()))};