var polylineMap=new Map;function createPolyLine(a){try{if(!polylineMap.containsKey(a.Key)){var b=[];for(i=0;i<a.Points.length;i++){var c=new BMap.Point(a.Points[i].Pointx,a.Points[i].Pointy);b[i]=c}var d=new BMap.Polyline(b,{strokeColor:a.StrokeColor,strokeWeight:a.StrokeWeight,strokeOpacity:a.StrokeOpacity});null!=a.Info&&(d.minfo=a.Info);d.addEventListener("click",onPolyLineClick);polylineMap.put(a.Key,d);map.addOverlay(d);return d}}catch(f){baiduMapException(3211,f,a.key)}return null}
function initPolyLine(a){try{objs=eval("("+a+")")}catch(b){baiduMapException(3111,b,a);return}for(i=0;i<objs.length;i++)createPolyLine(objs[i])}function deletePolyLine(a){a=eval(a);for(i=0;i<a.length;i++){var b=polylineMap.remove(a[i]);map.removeOverlay(b)}}function deleteAllPolyLine(){for(i=0;i<polylineMap.size();i++){var a=polylineMap.element(i).value;null!=a.getMap()&&map.removeOverlay(a)}polylineMap.clear()}
function updatePolyLine(a){try{var b=eval("("+a+")")}catch(c){return baiduMapException(3121,c,json),!1}for(i=0;i<b.length;i++){a=b[i];var d=polylineMap.get(a.Key);if(null==d)d=createPolyLine(a),map.addOverlay(d);else{if(null!=a.Points){var f=[];for(i=0;i<a.Points.length;i++){var e=new BMap.Point(a.Points[i].Pointx,a.Points[i].Pointy);f[i]=e}d.setPath(f)}null!=a.StrokeColor&&d.setStrokeColor(a.StrokeColor);null!=a.StrokeWeight&&d.setStrokeWeight(a.StrokeWeight);null!=a.StrokeOpacity&&d.setStrokeOpacity(a.StrokeOpacity);
null!=a.Info&&(d.minfo=a.Info)}}}function updatePolyLineWithoutInit(a,b,c,d,f){var e=polylineMap.get(a);if(null==e)return baiduMapException(3122,null,a),!1;if(null!=b){a=eval("("+b+")");b=[];for(i=0;i<a.length;i++){var g=new BMap.Point(a[i].Pointx,a[i].Pointy);b[i]=g}e.setPath(b)}null!=c&&e.setStrokeColor(c);null!=d&&e.setStrokeWeight(d);null!=f&&e.setStrokeOpacity(f);return!0}
function polyLineAddPoint(a,b){try{var c=eval("("+b+")")}catch(d){return baiduMapException(3122,d,a),null}var f=[];for(i=0;i<c.length;i++){var e=new BMap.Point(c[i].Pointx,c[i].Pointy);f[i]=e}c=polylineMap.get(a);null==c?(c=new BMap.Polyline(f,{strokeColor:DEFAULT_POLYLINE_TAIL_STROKECOLOR,strokeWeight:DEFAULT_POLYLINE_TAIL_STROKEWEIGHT,strokeOpacity:DEFAULT_POLYLINE_TAIL_STROKEOPACITY}),polylineMap.put(a,c),map.addOverlay(c)):(e=c.getPath(),e=e.concat(f),c.setPath(e))}
function isPolyLineExist(a){return polylineMap.containsKey(a)}function getPolyLineKeys(){return polylineMap.keys().toString()}function getPolyLineKeysOnShown(){var a=[],b=0;for(i=0;i<polylineMap.size();i++)null!=polylineMap.element(i).value.getMap()&&(a[b++]=polylineMap.element(i).key);return a.toString()}
function deletePolyLinesNotShown(){for(i=0;i<polylineMap.size();i++){var a=polylineMap.element(i).value;null==a.getMap()?polylineMap.removebyindex(i):a.isVisible()||(map.removeOverlay(a),polylineMap.removebyindex(i))}}function showPolyLines(a){a=eval(a);for(i=0;i<a.length;i++){var b=polylineMap.get(a[i]);null!=b?(null==b.getMap()&&map.addOverlay(b),null!=b.getMap()&&b.show()):baiduMapException(3131,null,a[i])}}
function hiddenPolyLines(a){a=eval(a);for(i=0;i<a.length;i++){var b=polylineMap.get(a[i]);null!=b?null!=b.getMap()&&b.hide():baiduMapException(3132,null,a[i])}}function showAllPolyLine(){for(i=0;i<polylineMap.size();i++){var a=polylineMap.element(i).value;null!=a&&null!=a.getMap&&a.show()}}function hiddenAllPolyLine(){for(i=0;i<polylineMap.size();i++){var a=polylineMap.element(i).value;null!=a&&null!=a.getMap&&a.hide()}}
function getPolyLinePoints(a){a=polylineMap.get(a);return null==a?null:a.getPath().toString()}function getPolyLineStrokeColor(a){a=polylineMap.get(a);return null==a?null:a.getStrokeColor()}function getPolyLineStrokeWeight(a){a=polylineMap.get(a);return null==a?null:a.getStrokeWeight()}function getPolyLineStrokeOpacity(a){a=polylineMap.get(a);return null==a?null:a.getStrokeOpacity()}function getPolyLineInfo(a){a=polylineMap.get(a);return null==a?null:a.minfo}
function setPolyLineInfo(a,b){var c=polylineMap.get(a);null!=c&&(c.minfo=b)}function isPolyLineShown(a){a=polylineMap.get(a);return null!=a&&null!=a.getMap()?!0:!1}function onPolyLineClick(a){var b=a.target;a=a.point;mInfoWindow.setTitle("");mInfoWindow.setContent(b.minfo);map.openInfoWindow(mInfoWindow,a)};