//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dlgDemo.rc
//
#define IDC_DEF_COLOR_BUTTON            3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DLGDEMO_DIALOG              102
#define IDD_COLORPROPERTYDLG_DIALOG     106
#define IDD_CODECSETTINGFRM_DIALOG      110
#define IDD_CVIDEODENOISEFRM_DIALOG     111
#define IDD_OSDSETTING_DIALOG           112
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDC_ST_DISPLAY                  1000
#define IDC_BT_START                    1001
#define IDC_BT_STEP_00                  1003
#define IDC_BT_STEP_01                  1004
#define IDC_BT_STEP_02                  1005
#define IDC_BT_STEP_03                  1006
#define IDC_BT_STEP_04                  1007
#define IDC_BT_STEP_05                  1008
#define IDC_BT_STEP_06                  1009
#define IDC_BT_STEP_07                  1010
#define IDC_BT_STEP_08                  1011
#define IDC_BT_DEINTERLACE              1012
#define IDC_BT_ASSIGN_AUDIO             1013
#define IDC_BT_PCOLOR                   1014
#define IDC_BT_BMP                      1015
#define IDC_BT_JPG                      1016
#define IDC_BT_CALLBACK                 1017
#define IDC_BT_DRAWFILE                 1018
#define IDC_ET_DRAWFILE                 1019
#define IDC_ST_DRAWFILE                 1020
#define IDC_BT_HIDEFILE                 1021
#define IDC_BT_TEXTOSD                  1022
#define IDC_BT_IMAGEOSD                 1023
#define IDC_BT_TIMEOSD                  1024
#define IDC_BT_FLIPVIDEO                1025
#define IDC_BT_MIRRORVIDEO              1026
#define IDC_BT_BUFDISPLAY               1027
#define IDC_BT_SOURCE                   1028
#define IDC_CB_SOURCES                  1029
#define IDC_BRIGHTNESS_STATIC           1031
#define IDC_CONTRAST_STATIC             1038
#define IDC_SATURATION_STATIC           1039
#define IDC_HUE_STATIC                  1040
#define IDC_SHARPNESS_STATIC            1041
#define IDC_COLOR_PROPERTY_BUTTON       1043
#define IDC_BT_RECORD                   1044
#define IDC_BRIGHTNESS_SLIDER           1048
#define IDC_CONTRAST_SLIDER             1049
#define IDC_SATURATION_SLIDER           1050
#define IDC_HUE_SLIDER                  1051
#define IDC_SHARPNESS_SLIDER            1052
#define IDOKEXIT                        1053
#define IDC_BUTTON_GetBuf               1055
#define IDC_BUTTON_SNAP                 1056
#define IDC_BUTTON_CALLSNAP             1057
#define IDC_BUTTON_EXIT                 1058
#define IDC_BUTTON_CODEC                1061
#define IDC_COMBO_VIDEOCODEC            1062
#define IDC_COMBO_AUDIOCODEC            1063
#define IDC_SLIDER_DENOISE              1063
#define IDC_STATIC_DENOISE              1064
#define IDC_BUTTON_PAUSEREC             1065
#define IDC_SLIDER_SHARP                1065
#define IDC_TIMEOSD_CHECK               1066
#define IDC_STATIC_SHARP                1066
#define IDC_TIMETRAN_CHECK              1067
#define IDC_STATIC_BRIGHT               1067
#define IDC_TimeFontSize_EDIT1          1068
#define IDC_STATIC_CONTRAST             1068
#define IDC_TimePlaceX_EDIT             1069
#define IDC_TimePlaceY_EDIT             1070
#define IDC_OSDSET_BUTTON               1072
#define IDC_BUTTON_COLOR2               1073
#define IDC_BUTTON_COLOR3               1074
#define IDC_BUTTON_COLOR1               1075
#define IDC_TEXTOSD_CHECK               1076
#define IDC_TEXTOSD_CHECK1              1076
#define IDC_TEXTTRAN_CHECK              1077
#define IDC_TEXTTRAN_CHECK1             1077
#define IDC_TextFontSize_EDIT2          1078
#define IDC_TextFontSize_EDIT1          1078
#define IDC_TEXTPlaceX_EDIT             1079
#define IDC_TEXTPlaceX_EDIT1            1079
#define IDC_TextPlaceY_EDIT             1080
#define IDC_TextPlaceY_EDIT1            1080
#define IDC_PICTUREOSD_CHECK            1081
#define IDC_PicturePlaceX_EDIT          1082
#define IDC_PicturePlaceY_EDIT          1083
#define IDC_TEXTOSD_CHECK2              1084
#define IDC_TEXTTRAN_CHECK2             1085
#define IDC_TextFontSize_EDIT3          1086
#define IDC_TEXTPlaceX_EDIT2            1087
#define IDC_TextPlaceY_EDIT2            1088
#define IDC_Texosd_EDIT4                1089
#define IDC_Texosd_EDIT5                1090
#define IDC_PictureFile_EDIT            1091
#define IDC_OPENFILE_BUTTON             1092
#define IDC_STATIC_CHANNEL              1093
#define IDC_SLIDER_BRIGHT               1094
#define IDC_SLIDER_CONTRACT             1095
#define IDC_RADIO_H264                  1095
#define IDC_RADIO_XVID                  1096
#define IDC_RADIO_DIVX                  1097
#define IDC_EDIT_SNAPDIR                1098
#define IDC_CAP_DIR_EDIT                1099
#define IDC_BUTTON_BROWSE_SNAPDIR       1100
#define IDC_BUTTON_BROWSE_RECDIR        1101
#define ID_SIZE_D1                      32771
#define ID_SIZE_CIF                     32772
#define ID_STAND_PAL                    32773
#define ID_STAND_NTSC                   32774
#define ID_SOUR_AV1                     32775
#define ID_SOUR_AV2                     32776
#define ID_SOUR_SVIDEO                  32777
#define ID_Flip_Video                   32779
#define ID_Mirror_Video                 32780
#define ID_Deinterlace_STD              32781
#define ID_Deinterlace_GOOD             32782
#define ID_Deinterlace_CANCEL           32783
#define ID_DENOISE_STD                  32784
#define ID_SIZE_768                     32785
#define ID_SIZE_960H                    32786
#define ID_Deinterlace_LowCpu           32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
